spring:
  mvc:
    log-request-details: false

  datasource:
    url: jdbc:mysql://localhost:3306/forohub?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: forohub
    password: forohub123

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    org.hibernate.SQL: off
    org.springframework.security: INFO
    com.forohub.auth: INFO

api:
  jwt:
    # CLAVE BASE64 (>=256 bits). Ejemplo:
    secret: U29uVWFuQ2xhdmVzQm9uaXRhcy0xMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Ng==
    ttl-seconds: 7200

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
