blank_issues_enabled: false
contact_links:
  - name: Pregunta general / ayuda
    url: https://github.com/kennysolorzano/forohub/discussions
    about: Usa las discusiones para dudas no relacionadas con bugs o features.
